services:
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  ch:
    image: "valkey/valkey:alpine"
    ports:
      - "6379:6379"

  app:
    image: "python:alpine"
    working_dir: "/app"
    volumes:
      - "./:/app"
    depends_on:
      - "db"
    ports:
      - 8000:8000
    command: >
      sh -c "pip install .
      && python -m scripts.init_db
      && uvicorn main:app --host 0.0.0.0 --port 8000
      "
